#!/bin/bash
# Script to run AIMS for multiple input files and edit the configuration file
# with each iteration.

#cd /home/bmr135/AIMS_New
file="/home/bmr135/AIMS/AIMS_BEN/NGC6819_list"
while IFS= read -r line
do
	# cp -f /home/bmr135/AIMS_New/Art_tests_round_2/"$line" AIMS_configure.py
	# printf '%s\n' "$line"
	python AIMS.py "$line"
done < "$file"
