#!/bin/bash

#for FOLDER in $(find /home/buldgen/mnt/rds//GRIDPARAM_Diffusion -maxdepth 1 -mindepth 1 -type d);
#for FOLDER in $(find /home/buldgen/GridGiantsClesV0.3/models_grad_rad_under -maxdepth 1 -mindepth 1 -type d);
#for FOLDER in $(find /home/buldgen/osc-42.2_new/TestComputeP0 -maxdepth 1 -mindepth 1 -type d);
#for FOLDER in $(find /home/ADF/bmr135/Sim3/cles-19.1-Up/scripts -maxdepth 1 -mindepth 1 -type d);
i=0
for FOLDER in $(find /home/bmr135/bison/NGC6791_final -maxdepth 1 -mindepth 1 -type d);
do
 echo $FOLDER, 1
 FOLDERNAME=$(echo $FOLDER | cut -d "/" -f 8)
 echo $FOLDERNAME, 2
 cd $FOLDER
   #mkdir AIMSGBKP
#  for file in $(ls -f *.freq);
#  do
#  echo $file
#  mv $file ./AIMSG
#    echo $file
#    computeP0 $file
  #COUNTER=1
    #echo $file
    #while read -a line ; do
     # if (($COUNTER == 4)); then
     #   echo "$file ${line[0]} ${line[1]} ${line[2]}">> /home/buldgen/TrackTest/Track$FOLDERNAME.txt
      #fi
      #if (($COUNTER > 7)) && (($COUNTER <= 10)); then
      #  echo "$file ${line[0]} ${line[1]} ${line[4]}">> /home/buldgen/TrackTest/Modes$FOLDERNAME.txt

      #fi
      #COUNTER=$[$COUNTER +1]
    #done <"$file"
#  done
#  mv *.p0 /home/buldgen/GridGiantsClesV0.3/tracks
#  cd ../
#done

#cd /home/ADF/bmr135/Sim3/cles-19.1-Up/scripts/M1.06.X0.716.Z0.0175

for file in $(ls -f *.txt);
do
  echo $file, 3
  ~/AIMS/AIMS_BEN/generateList $file
  i=`expr $i + 1`
  echo $i
done
done
